---
title: "Welcome"
author: "CP/TK"
date: "2023-01-15"
format:
  revealjs:
    logo: logo.jpg
    slide-number: true
fragmentInURL: true
---

## Organizational issues

- Breakfast 07:30-09:00 | lunch 12:00 | dinner 19:00
- Please join the slack
- Twitter [#EuBIC2023](https://twitter.com/hashtag/EuBIC2023?src=hashtag_click) 

## Sunday

::: {style="font-size: 0.70em; "}
- 16:00 - Welcome address by CSF and EuBIC-MS
- 16:15 - Keynotes
  - Open Search: Open-minded Exploration of Proteomics Data <br> Alexey I. Nesvizhskii
  - Towards the next generation of proteomics analysis with the AlphaPept ecosystem <br> Maximilian Strauss
- 17:45 - Coffe break 
- 18:05 - Setup/sort poster presenters
- 18:15 - Poster flash talks
- 19:00 - Apéro Riche (in combination with the Poster Session)
- 21:15 - Shuttle leaves for external hotel
:::

## Monday 2023-01-16

::: {style="font-size: 0.70em; "}
- 07:30 - 09:00 breakfast
- 08:00 Shuttle service between external hotel and CSF leaves at Raiffeisen Bank
- 09:00 Keynotes
  - 09:00 The DOME Recommendations for Machine Learning Exemplified on Prosit <br> Mathias Wilhelm
  - 10:30 Predicting physiochemical properties of peptides using deep learning <br> Anna Klimovskaia Susmelj
  - 11:15 Towards a structurally resolved human protein interaction network <br> Pedro Beltrao
- 12:00 Lunch
- 13:30 Hackathon presentations
- Have fun with hackathon team
:::

## Important locations

```{r}
#| echo: false
#| fig-height: 6
library(leaflet)
leaflet::leaflet() |>
  leaflet::addTiles() |>
  leaflet::addMarkers(lng=8.7631, lat=46.1584, popup="Monte Verita") |>
  leaflet::addMarkers(lng=8.7702, lat=46.1533, popup="Ristorante Osteria Nostrana") |>
  leaflet::addMarkers(lng=8.7943, lat=46.1686, popup="Hotel DELL'ANGELO")
```
